### PR TITLE
item list

### PR DESCRIPTION
**Pull request by annedhyacinthe**
Simulator Screenshot - iPhone SE (3rd generation) - 2023-07-21 at 21 08 24

### CODE REVIEW

**Comment by Jarr1t** [comment]
Would the next step here be to assign the food items to the users?

**Comment by annedhyacinthe** [comment]
> Would the next step here be to assign the food items to the users?

Yes but first state would have to be created for the users and their orders and I'm doing that now

**Review by Jarr1t — APPROVED** [review]
LGTM!

**Comment by antsanchez198** [comment]
Looks good!

**Review by antsanchez198 — APPROVED** [review]

**Pull request merged**
